# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import status_pb2 as status__pb2


class StatusServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchStatus = channel.unary_unary(
                '/status.StatusService/FetchStatus',
                request_serializer=status__pb2.StatusRequest.SerializeToString,
                response_deserializer=status__pb2.StatusResponse.FromString,
                )


class StatusServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchStatus,
                    request_deserializer=status__pb2.StatusRequest.FromString,
                    response_serializer=status__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'status.StatusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StatusService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/status.StatusService/FetchStatus',
            status__pb2.StatusRequest.SerializeToString,
            status__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
