services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017/tcp"

  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306/tcp"
    volumes:
      - ./data/mysql-seed.sql:/docker-entrypoint-initdb.d/mysql-seed.sql
    environment:
      MYSQL_DATABASE: mono
      MYSQL_ROOT_PASSWORD: pass

  postgres:
    image: postgres
    ports:
      - "5432/tcp"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:alpine
    ports:
      - "6379/tcp"

  grpc-srvr:
    image: grpc-srvc
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.grpc-srvr
    ports:
      - 50051:50051
    environment:
      MONO_GRPC_PORT: $MONO_GRPC_PORT
      MONO_MONGO_DSN: $MONO_MONGO_DSN
      MONO_MYSQL_DSN: $MONO_MYSQL_DSN
      MONO_POSTGRES_DSN: $MONO_POSTGRES_DSN
      MONO_REDIS_DSN: $MONO_REDIS_DSN
      MONO_SERVICE_NAME: $MONO_SERVICE_NAME

