[tool.poetry]
name = "mono-http"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.72.0"
uvicorn = "^0.17.0"
hello-two = {path = "../../pkg/hello-two"}

[tool.poetry.dev-dependencies]
pytest = "^6.2"
