# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status/v1/status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16status/v1/status.proto\x12\tstatus.v1\"\x14\n\x12\x46\x65tchStatusRequest\"I\n\x13\x46\x65tchStatusResponse\x12\x18\n\x07healthy\x18\x01 \x01(\x08R\x07healthy\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message2_\n\rStatusService\x12N\n\x0b\x46\x65tchStatus\x12\x1d.status.v1.FetchStatusRequest\x1a\x1e.status.v1.FetchStatusResponse\"\x00\x42\x98\x01\n\rcom.status.v1B\x0bStatusProtoP\x01Z5github.com/mikedonnici/mono/go/gen/status/v1;statusv1\xa2\x02\x03SXX\xaa\x02\tStatus.V1\xca\x02\tStatus\\V1\xe2\x02\x15Status\\V1\\GPBMetadata\xea\x02\nStatus::V1b\x06proto3')



_FETCHSTATUSREQUEST = DESCRIPTOR.message_types_by_name['FetchStatusRequest']
_FETCHSTATUSRESPONSE = DESCRIPTOR.message_types_by_name['FetchStatusResponse']
FetchStatusRequest = _reflection.GeneratedProtocolMessageType('FetchStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHSTATUSREQUEST,
  '__module__' : 'status.v1.status_pb2'
  # @@protoc_insertion_point(class_scope:status.v1.FetchStatusRequest)
  })
_sym_db.RegisterMessage(FetchStatusRequest)

FetchStatusResponse = _reflection.GeneratedProtocolMessageType('FetchStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _FETCHSTATUSRESPONSE,
  '__module__' : 'status.v1.status_pb2'
  # @@protoc_insertion_point(class_scope:status.v1.FetchStatusResponse)
  })
_sym_db.RegisterMessage(FetchStatusResponse)

_STATUSSERVICE = DESCRIPTOR.services_by_name['StatusService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.status.v1B\013StatusProtoP\001Z5github.com/mikedonnici/mono/go/gen/status/v1;statusv1\242\002\003SXX\252\002\tStatus.V1\312\002\tStatus\\V1\342\002\025Status\\V1\\GPBMetadata\352\002\nStatus::V1'
  _FETCHSTATUSREQUEST._serialized_start=37
  _FETCHSTATUSREQUEST._serialized_end=57
  _FETCHSTATUSRESPONSE._serialized_start=59
  _FETCHSTATUSRESPONSE._serialized_end=132
  _STATUSSERVICE._serialized_start=134
  _STATUSSERVICE._serialized_end=229
# @@protoc_insertion_point(module_scope)
