# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import attribute_pb2 as attribute__pb2


class AttributeServiceStub(object):
    """Separate services for FetchOne and FetchMany ??
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchAttribute = channel.unary_unary(
                '/attribute.AttributeService/FetchAttribute',
                request_serializer=attribute__pb2.FetchAttributeRequest.SerializeToString,
                response_deserializer=attribute__pb2.FetchAttributeResponse.FromString,
                )


class AttributeServiceServicer(object):
    """Separate services for FetchOne and FetchMany ??
    """

    def FetchAttribute(self, request, context):
        """rpc AddAttribute(FetchAttributeRequest) returns (FetchAttributeResponse) {};
        rpc ChangeAttribute(FetchAttributeRequest) returns (FetchAttributeResponse) {};
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttributeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchAttribute,
                    request_deserializer=attribute__pb2.FetchAttributeRequest.FromString,
                    response_serializer=attribute__pb2.FetchAttributeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'attribute.AttributeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AttributeService(object):
    """Separate services for FetchOne and FetchMany ??
    """

    @staticmethod
    def FetchAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/attribute.AttributeService/FetchAttribute',
            attribute__pb2.FetchAttributeRequest.SerializeToString,
            attribute__pb2.FetchAttributeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
