# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attribute.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='attribute.proto',
  package='attribute',
  syntax='proto3',
  serialized_options=b'Z\'github.com/mikedonnici/mono/go/attribute',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61ttribute.proto\x12\tattribute\"3\n\tAttribute\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"K\n\x15\x46\x65tchAttributeRequest\x12\x0f\n\x02id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x11\n\x04type\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x07\n\x05_type\"A\n\x16\x46\x65tchAttributeResponse\x12\'\n\tattribute\x18\x01 \x01(\x0b\x32\x14.attribute.Attribute2k\n\x10\x41ttributeService\x12W\n\x0e\x46\x65tchAttribute\x12 .attribute.FetchAttributeRequest\x1a!.attribute.FetchAttributeResponse\"\x00\x42)Z\'github.com/mikedonnici/mono/go/attributeb\x06proto3'
)




_ATTRIBUTE = _descriptor.Descriptor(
  name='Attribute',
  full_name='attribute.Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='attribute.Attribute.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='attribute.Attribute.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='attribute.Attribute.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=81,
)


_FETCHATTRIBUTEREQUEST = _descriptor.Descriptor(
  name='FetchAttributeRequest',
  full_name='attribute.FetchAttributeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='attribute.FetchAttributeRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='attribute.FetchAttributeRequest.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_id', full_name='attribute.FetchAttributeRequest._id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_type', full_name='attribute.FetchAttributeRequest._type',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=83,
  serialized_end=158,
)


_FETCHATTRIBUTERESPONSE = _descriptor.Descriptor(
  name='FetchAttributeResponse',
  full_name='attribute.FetchAttributeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attribute', full_name='attribute.FetchAttributeResponse.attribute', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=225,
)

_FETCHATTRIBUTEREQUEST.oneofs_by_name['_id'].fields.append(
  _FETCHATTRIBUTEREQUEST.fields_by_name['id'])
_FETCHATTRIBUTEREQUEST.fields_by_name['id'].containing_oneof = _FETCHATTRIBUTEREQUEST.oneofs_by_name['_id']
_FETCHATTRIBUTEREQUEST.oneofs_by_name['_type'].fields.append(
  _FETCHATTRIBUTEREQUEST.fields_by_name['type'])
_FETCHATTRIBUTEREQUEST.fields_by_name['type'].containing_oneof = _FETCHATTRIBUTEREQUEST.oneofs_by_name['_type']
_FETCHATTRIBUTERESPONSE.fields_by_name['attribute'].message_type = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['Attribute'] = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['FetchAttributeRequest'] = _FETCHATTRIBUTEREQUEST
DESCRIPTOR.message_types_by_name['FetchAttributeResponse'] = _FETCHATTRIBUTERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Attribute = _reflection.GeneratedProtocolMessageType('Attribute', (_message.Message,), {
  'DESCRIPTOR' : _ATTRIBUTE,
  '__module__' : 'attribute_pb2'
  # @@protoc_insertion_point(class_scope:attribute.Attribute)
  })
_sym_db.RegisterMessage(Attribute)

FetchAttributeRequest = _reflection.GeneratedProtocolMessageType('FetchAttributeRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHATTRIBUTEREQUEST,
  '__module__' : 'attribute_pb2'
  # @@protoc_insertion_point(class_scope:attribute.FetchAttributeRequest)
  })
_sym_db.RegisterMessage(FetchAttributeRequest)

FetchAttributeResponse = _reflection.GeneratedProtocolMessageType('FetchAttributeResponse', (_message.Message,), {
  'DESCRIPTOR' : _FETCHATTRIBUTERESPONSE,
  '__module__' : 'attribute_pb2'
  # @@protoc_insertion_point(class_scope:attribute.FetchAttributeResponse)
  })
_sym_db.RegisterMessage(FetchAttributeResponse)


DESCRIPTOR._options = None

_ATTRIBUTESERVICE = _descriptor.ServiceDescriptor(
  name='AttributeService',
  full_name='attribute.AttributeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=227,
  serialized_end=334,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchAttribute',
    full_name='attribute.AttributeService.FetchAttribute',
    index=0,
    containing_service=None,
    input_type=_FETCHATTRIBUTEREQUEST,
    output_type=_FETCHATTRIBUTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ATTRIBUTESERVICE)

DESCRIPTOR.services_by_name['AttributeService'] = _ATTRIBUTESERVICE

# @@protoc_insertion_point(module_scope)
