// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: redisdata/v1/redisdata.proto

package redisdatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataMessage represents data from redis
type DataMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DataMessage) Reset() {
	*x = DataMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redisdata_v1_redisdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessage) ProtoMessage() {}

func (x *DataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_redisdata_v1_redisdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessage.ProtoReflect.Descriptor instead.
func (*DataMessage) Descriptor() ([]byte, []int) {
	return file_redisdata_v1_redisdata_proto_rawDescGZIP(), []int{0}
}

func (x *DataMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// FetchDataRequest
type FetchDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FetchDataRequest) Reset() {
	*x = FetchDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redisdata_v1_redisdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataRequest) ProtoMessage() {}

func (x *FetchDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redisdata_v1_redisdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataRequest.ProtoReflect.Descriptor instead.
func (*FetchDataRequest) Descriptor() ([]byte, []int) {
	return file_redisdata_v1_redisdata_proto_rawDescGZIP(), []int{1}
}

func (x *FetchDataRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// FetchDataResponse
type FetchDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *DataMessage `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FetchDataResponse) Reset() {
	*x = FetchDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redisdata_v1_redisdata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataResponse) ProtoMessage() {}

func (x *FetchDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redisdata_v1_redisdata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataResponse.ProtoReflect.Descriptor instead.
func (*FetchDataResponse) Descriptor() ([]byte, []int) {
	return file_redisdata_v1_redisdata_proto_rawDescGZIP(), []int{2}
}

func (x *FetchDataResponse) GetData() *DataMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_redisdata_v1_redisdata_proto protoreflect.FileDescriptor

var file_redisdata_v1_redisdata_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x65, 0x64, 0x69, 0x73, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x72,
	0x65, 0x64, 0x69, 0x73, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x72, 0x65, 0x64, 0x69, 0x73, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x22, 0x33, 0x0a, 0x0b,
	0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x22, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x65, 0x64, 0x69, 0x73,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x62, 0x0a, 0x10, 0x52, 0x65, 0x64,
	0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a,
	0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x2e, 0x72, 0x65, 0x64,
	0x69, 0x73, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x65, 0x64,
	0x69, 0x73, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0xb0, 0x01,
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x64, 0x69, 0x73, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x76, 0x31, 0x42, 0x0e, 0x52, 0x65, 0x64, 0x69, 0x73, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x69, 0x6b, 0x65, 0x64, 0x6f, 0x6e, 0x6e, 0x69, 0x63, 0x69, 0x2f, 0x6d, 0x6f, 0x6e,
	0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x2f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x64, 0x61,
	0x74, 0x61, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x65, 0x64, 0x69, 0x73, 0x64, 0x61, 0x74, 0x61, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x52, 0x58, 0x58, 0xaa, 0x02, 0x0c, 0x52, 0x65, 0x64, 0x69, 0x73, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0c, 0x52, 0x65, 0x64, 0x69, 0x73, 0x64, 0x61,
	0x74, 0x61, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x18, 0x52, 0x65, 0x64, 0x69, 0x73, 0x64, 0x61, 0x74,
	0x61, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x0d, 0x52, 0x65, 0x64, 0x69, 0x73, 0x64, 0x61, 0x74, 0x61, 0x3a, 0x3a, 0x56, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_redisdata_v1_redisdata_proto_rawDescOnce sync.Once
	file_redisdata_v1_redisdata_proto_rawDescData = file_redisdata_v1_redisdata_proto_rawDesc
)

func file_redisdata_v1_redisdata_proto_rawDescGZIP() []byte {
	file_redisdata_v1_redisdata_proto_rawDescOnce.Do(func() {
		file_redisdata_v1_redisdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_redisdata_v1_redisdata_proto_rawDescData)
	})
	return file_redisdata_v1_redisdata_proto_rawDescData
}

var file_redisdata_v1_redisdata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_redisdata_v1_redisdata_proto_goTypes = []interface{}{
	(*DataMessage)(nil),       // 0: redisdata.v1.DataMessage
	(*FetchDataRequest)(nil),  // 1: redisdata.v1.FetchDataRequest
	(*FetchDataResponse)(nil), // 2: redisdata.v1.FetchDataResponse
}
var file_redisdata_v1_redisdata_proto_depIdxs = []int32{
	0, // 0: redisdata.v1.FetchDataResponse.data:type_name -> redisdata.v1.DataMessage
	1, // 1: redisdata.v1.RedisDataService.FetchData:input_type -> redisdata.v1.FetchDataRequest
	2, // 2: redisdata.v1.RedisDataService.FetchData:output_type -> redisdata.v1.FetchDataResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_redisdata_v1_redisdata_proto_init() }
func file_redisdata_v1_redisdata_proto_init() {
	if File_redisdata_v1_redisdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_redisdata_v1_redisdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redisdata_v1_redisdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redisdata_v1_redisdata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redisdata_v1_redisdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redisdata_v1_redisdata_proto_goTypes,
		DependencyIndexes: file_redisdata_v1_redisdata_proto_depIdxs,
		MessageInfos:      file_redisdata_v1_redisdata_proto_msgTypes,
	}.Build()
	File_redisdata_v1_redisdata_proto = out.File
	file_redisdata_v1_redisdata_proto_rawDesc = nil
	file_redisdata_v1_redisdata_proto_goTypes = nil
	file_redisdata_v1_redisdata_proto_depIdxs = nil
}
