name: ci

on:
  push:
    branches:
      - 'main'

env:
  GAR_URL: australia-southeast1-docker.pkg.dev
  IMAGE_NAME: mono-grpc-srvr
  PROJECT_ID: mono-346800

jobs:
  build-and-push-gcr:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: |-
          gcloud auth configure-docker
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: Build and Push Container
        env:
          IMAGE_SHA: ${{ GAR_URL }}/${{ env.PROJECT_ID }}/mono/${{ env.IMAGE_NAME }}:${{ github.sha }}
          IMAGE_LATEST: ${{ GAR_URL }}/${{ env.PROJECT_ID }}/mono/${{ env.IMAGE_NAME }}:latest
        run: |-
          docker build -f ./Dockerfile.grpc-srvr -t $IMAGE_SHA .
          docker tag $IMAGE_SHA $IMAGE_LATEST
          docker push $IMAGE_SHA    
          docker push $IMAGE_LATEST
