name: deploy-qa

on:
  push:
    branches:
      - main
    tags:
      - qa-*
  workflow_dispatch:

jobs:
  deploy-to-qa:

    name: Deploy to QA
    runs-on: ubuntu-latest
    steps:

      - name: Source names
        id: source_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}  

      - name: Echo names
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
        env:
          SOURCE_NAME: ${{ steps.source_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.source_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.source_name.outputs.SOURCE_TAG }}

      - name: echo
        env:
          SOURCE_TAG: ${{ steps.source_name.outputs.SOURCE_TAG }}
        run: |
          echo "Deploying release $SOURCE_TAG to QA environment"
