name: ci-grpc-srvr

on:
  push:
    branches:
      - 'main'
    paths:
      - 'go/**'
  workflow_dispatch:

env:
  PROJECT_ID: mono-346800
  GAR_URL: australia-southeast1-docker.pkg.dev
  GAR_REPO: mono
  IMAGE_NAME: grpc-srvr

jobs:
  build-and-push-gar:
    name: Build and Push to GAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: |-
          gcloud auth configure-docker
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: Build and Push Container
        env:
          IMAGE_SHA: ${{ env.GAR_URL }}/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          IMAGE_LATEST: ${{ env.GAR_URL }}/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:latest
        run: |-
          echo IMAGE_SHA=$IMAGE_SHA
          echo IMAGE_LATEST=$IMAGE_LATEST
          docker build -f ./Dockerfile.grpc-srvr -t $IMAGE_SHA .
          docker tag $IMAGE_SHA $IMAGE_LATEST
          docker push $IMAGE_SHA    
          docker push $IMAGE_LATEST
